name: tests

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    strategy:
      matrix:
        php: ['8.1', '8.2']
        illuminate: ['8.22.1', '8.83', '9.0', '9.52', '10.0', '10.31']
    name: PHP ${{ matrix.php }} Illuminate ${{ matrix.illuminate }}
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: Installing PHP
        uses: shivammathur/setup-php@master
        with:
          php-version: ${{ matrix.php }}
          extensions: mbstring, json, sqlite3, apcu
          ini-values: apc.enable_cli=1
          tools: composer:v2
      - name: Lock Illuminate Package Versions
        run: composer require "illuminate/http:${{ matrix.illuminate }}.*" --no-update -v && composer require "illuminate/collections:${{ matrix.illuminate }}.*" --no-update -v && composer require "illuminate/cache:${{ matrix.illuminate }}.*" --no-update -v
      - name: Composer Install
        run: composer install --prefer-dist --no-progress --no-interaction
      - name: Run Tests
        run: php vendor/bin/phpunit --testdox
